// Vorlesetexte fürs Stimmprofil: je Sprache elf Texte von etwa 25–35 Sekunden Lesedauer.
// Bewusst unterschiedliche Szenen, Satzmelodien und Laute (Fragen, Ausrufe, wörtliche Rede, Zahlen),
// damit der Stimmabdruck nicht nur auf einer Tonlage beruht. Kein t(): eigener Text pro Sprache.

/** Pro App-Sprache; für Sprachen ohne eigene Texte nimmt die App die englischen (siehe readingTextsFor) */
export const READING_TEXTS: Partial<Record<string, string[]>> & { de: string[]; en: string[] } = {
  de: [
    'Der Wind trug den Geruch von Regen über die Dächer von Kaltenfurt. Am Hafen zählte ein alter Fährmann seine Münzen: sieben aus Kupfer, zwei aus Silber und eine, die er nicht kannte. Irgendwo schlug eine Glocke, obwohl es noch lange nicht Mitternacht war. „Wer will um diese Stunde noch übersetzen?“, fragte er leise, doch niemand antwortete. Nur die Raben auf dem Mast legten die Köpfe schief und warteten.',
    'Im Keller der alten Zollstation roch es nach Öl und nassem Stein. Mira hob die Laterne und zählte die Fässer: vierzehn, fünfzehn, sechzehn – eines fehlte. Auf dem Boden glänzte eine Spur aus Wachs, die unter der Treppe verschwand. „Wir sind nicht allein“, flüsterte sie, und irgendwo über ihnen knarrte eine Tür, als hätte jemand genau auf diesen Satz gewartet.',
    'Drei Tage lang hatte die Karawane keinen Brunnen gesehen. Die Kamele trotteten schweigend, und der Sand verschluckte jedes Geräusch. Dann, kurz vor Sonnenuntergang, zeigte der Führer auf einen dunklen Punkt am Horizont. „Das ist kein Felsen“, sagte er heiser. „Das ist ein Turm, und gestern stand er noch nicht dort.“ Niemand lachte über den Scherz, denn es war keiner.',
    'Der Regen auf den Neonschildern färbte die Straße violett. Juno zog die Kapuze tiefer und prüfte zum dritten Mal den Chip in ihrer Handfläche. Zwölf Minuten bis zur Übergabe, zwei Drohnen über der Kreuzung und ein Verkäufer, der viel zu freundlich lächelte. „Nudeln, frisch aus dem Automaten?“, rief er. Sie nickte, bezahlte und wusste sofort, dass die Suppe nur ein Vorwand war.',
    'Oben am Pass pfiff der Wind so scharf, dass die Worte an den Lippen gefroren. Borin band das Seil zweimal um den Felsen und prüfte jeden Knoten. Unter ihnen lag das Tal im Nebel, über ihnen kreiste ein Adler, groß wie ein Wagen. „Noch hundert Schritte“, sagte er, „dann sind wir am Kloster.“ Hinter der nächsten Biegung hörten sie Gesang, obwohl dort seit Jahren niemand mehr wohnte.',
    'Auf dem Marktplatz von Weidenbrück wurde gefeilscht, gelacht und gelogen, wie an jedem Donnerstag. Ein Gaukler balancierte sieben Teller auf einem Stock, eine Händlerin pries Äpfel an, die angeblich aus dem Garten eines Königs stammten. Zwischen den Ständen schlich ein Junge mit flinken Fingern. Er ahnte nicht, dass ihm der Beutel, den er gleich stehlen würde, mehr Ärger einbringen sollte als alle anderen zusammen.',
    'Die Möwen kreischten, als die Silberne Muschel den Hafen verließ. Kapitänin Rhea stand am Steuer und rief Befehle, die der Wind zerriss: Segel setzen, Leinen los, Kurs Südwest! Die Mannschaft gehorchte schneller als sonst, denn alle hatten die schwarzen Wolken gesehen. Nur der alte Koch blieb gelassen, schälte Kartoffeln und murmelte, das Meer sei heute launisch, aber nicht böse.',
    'Auf der Wiese hinter der Mühle blühten Kornblumen und Mohn. Die Kinder jagten Schmetterlinge, der Müller schlief im Schatten einer Eiche, und über allem summte der Sommer. Nur die alte Katze saß unbeweglich am Wegrand und starrte zum Waldrand hinüber. Dort bewegte sich etwas zwischen den Stämmen, langsam und vorsichtig, als wüsste es genau, dass es beobachtet wurde.',
    'Die Fackel flackerte, als Tamsin die letzte Stufe hinabstieg. Die Wände waren mit Runen bedeckt, manche eingeritzt, andere mit Kohle gemalt. In der Mitte des Raumes stand eine Truhe, viel zu sauber für einen Ort, den seit Jahrhunderten niemand betreten haben sollte. „Wer zuerst die Falle findet, bekommt den größeren Anteil“, sagte Garrek und grinste. Niemand rührte sich.',
    'Auf der Brücke der Aurora war es still bis auf das leise Summen der Maschinen. Auf dem Hauptschirm drehte sich ein Planet in Bernstein und Grau, umgeben von drei Monden. „Keine Lebenszeichen“, meldete der Navigator, „aber eine Energiesignatur unter dem Eis.“ Die Kommandantin trank ihren Kaffee aus, stellte den Becher ab und ließ die Landefähre vorbereiten. Sie hasste Überraschungen, doch sie liebte Rätsel.',
    'Im Gasthaus Zum Schiefen Humpen war es voll, laut und warm. Am Kamin erzählte ein Barde von einem Drachen, der angeblich Gedichte sammelte, und die Zuhörer klopften begeistert auf die Tische. Die Wirtin stellte vier Krüge vor die Fremden in der Ecke und sagte leise: „Der Mann an der Tür fragt nach euch. Er trägt das Wappen des Grafen, und fröhlich sieht er nicht aus.“'
  ],
  en: [
    'The wind carried the smell of rain across the rooftops of Coldford. Down at the harbour, an old ferryman counted his coins: seven of copper, two of silver, and one he did not recognise. Somewhere a bell was ringing, although midnight was still hours away. "Who would want to cross at this hour?" he asked quietly, but nobody answered. Only the ravens on the mast tilted their heads and waited.',
    'The cellar of the old customs house smelled of oil and wet stone. Mira raised her lantern and counted the barrels: fourteen, fifteen, sixteen – one was missing. A trail of wax gleamed on the floor and vanished beneath the stairs. "We\'re not alone," she whispered, and somewhere above them a door creaked, as if someone had been waiting for exactly those words.',
    'For three days the caravan had not seen a single well. The camels plodded on in silence, and the sand swallowed every sound. Then, just before sunset, the guide pointed at a dark speck on the horizon. "That\'s no rock," he said hoarsely. "That\'s a tower, and it wasn\'t there yesterday." Nobody laughed at the joke, because it wasn\'t one.',
    'Rain on the neon signs turned the street violet. Juno pulled her hood lower and checked the chip in her palm for the third time. Twelve minutes until the handover, two drones above the crossing, and a vendor who was smiling far too kindly. "Fresh noodles, straight from the machine?" he called. She nodded, paid, and knew at once that the soup was only an excuse.',
    'Up on the pass, the wind whistled so sharply that the words froze on their lips. Borin wrapped the rope twice around the rock and checked every knot. Below them the valley lay in fog; above them an eagle the size of a cart was circling. "A hundred more steps," he said, "and we\'ll reach the monastery." Round the next bend they heard singing, although nobody had lived there for years.',
    'In the market square of Willowbridge, people haggled, laughed and lied, just as they did every Thursday. A juggler balanced seven plates on a stick, and a trader praised apples that supposedly came from a king\'s own garden. Between the stalls crept a boy with quick fingers. He had no idea that the purse he was about to steal would bring him more trouble than all the others put together.',
    'The gulls screamed as the Silver Shell left the harbour. Captain Rhea stood at the wheel and shouted orders that the wind tore apart: set the sails, cast off, course south-west! The crew obeyed faster than usual, because everyone had seen the black clouds. Only the old cook stayed calm, peeling potatoes and muttering that the sea was moody today, but not cruel.',
    'Cornflowers and poppies bloomed in the meadow behind the mill. The children chased butterflies, the miller slept in the shade of an oak, and summer hummed over everything. Only the old cat sat perfectly still at the edge of the path, staring at the treeline. Something was moving between the trunks, slowly and carefully, as if it knew exactly that it was being watched.',
    'The torch flickered as Tamsin stepped down the last stair. The walls were covered in runes, some carved, others drawn in charcoal. In the middle of the room stood a chest, far too clean for a place nobody was supposed to have entered for centuries. "Whoever finds the trap first gets the bigger share," said Garrek with a grin. Nobody moved.',
    'The bridge of the Aurora was silent except for the soft hum of the engines. On the main screen, a planet of amber and grey was turning, circled by three moons. "No signs of life," the navigator reported, "but there\'s an energy signature under the ice." The commander finished her coffee, put down the mug and ordered the lander to be prepared. She hated surprises, but she loved puzzles.',
    'The Crooked Tankard was full, loud and warm. By the fire, a bard told of a dragon who supposedly collected poems, and the listeners drummed on the tables with delight. The landlady set four mugs in front of the strangers in the corner and said quietly, "The man at the door is asking about you. He wears the count\'s coat of arms, and he doesn\'t look happy."'
  ]
};

/** Zufälliger Text, möglichst nicht derselbe wie zuletzt */
export function readingTextsFor(lang: string): string[] {
  return READING_TEXTS[lang] ?? READING_TEXTS.en;
}

export function pickReadingText(lang: string, not?: number): number {
  const n = readingTextsFor(lang).length;
  let i = Math.floor(Math.random() * n);
  if (n > 1 && i === not) i = (i + 1 + Math.floor(Math.random() * (n - 1))) % n;
  return i;
}
